#!/usr/bin/env python3
"""Generate src/ui/icons.ts from the compose module's vector drawables.

The compose flavour IS the app's UI, so its drawables are the icon source of truth.
Re-run after the app/compose drawables change:

    python3 scripts/gen-icons.py
"""
import json, os, re, sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, '../../../../android/farmerchat-android-compose/src/main/res/drawable'))
OUT = os.path.join(HERE, '../src/ui/icons.ts')
A = '{http://schemas.android.com/apk/res/android}'

def color(c):
    if not c: return None
    c = c.strip()
    if c.startswith('@'): return None  # resource refs resolve to the tint at runtime
    m = re.fullmatch(r'#([0-9a-fA-F]{8})', c)
    if m:
        h = m.group(1); a = int(h[:2], 16) / 255
        return f'#{h[2:]}' if a >= 0.999 else f'rgba({int(h[2:4],16)},{int(h[4:6],16)},{int(h[6:],16)},{a:.3f})'
    return c

def dp(v): return float(re.sub(r'(dp|dip)$', '', v))

icons = {}
for f in sorted(os.listdir(SRC)):
    if not f.endswith('.xml'): continue
    root = ET.parse(os.path.join(SRC, f)).getroot()
    if root.tag != 'vector': continue
    paths = []
    for p in root.iter('path'):
        d = {'d': p.get(A + 'pathData')}
        fill = color(p.get(A + 'fillColor'))
        stroke = color(p.get(A + 'strokeColor'))
        d['fill'] = fill or 'none'
        if stroke:
            d['stroke'] = stroke
            d['strokeWidth'] = float(p.get(A + 'strokeWidth', '1'))
            for k, a in (('strokeLinecap', 'strokeLineCap'), ('strokeLinejoin', 'strokeLineJoin')):
                if p.get(A + a): d[k] = p.get(A + a)
        if p.get(A + 'fillType') == 'evenOdd': d['fillRule'] = 'evenodd'
        if p.get(A + 'fillAlpha'): d['fillOpacity'] = float(p.get(A + 'fillAlpha'))
        if p.get(A + 'strokeAlpha'): d['strokeOpacity'] = float(p.get(A + 'strokeAlpha'))
        paths.append(d)
    name = f[:-4].removeprefix('fc_')
    icons[name] = {
        'w': dp(root.get(A + 'width')), 'h': dp(root.get(A + 'height')),
        'vw': float(root.get(A + 'viewportWidth')), 'vh': float(root.get(A + 'viewportHeight')),
        'paths': paths,
    }

# Material Icons used by compose (`Icons.Filled.Close` …), from the official Material Icons
# SVG set (Apache-2.0), extracted once into scripts/material-icons.json and prefixed `m_`.
for k, v in json.load(open(os.path.join(HERE, 'material-icons.json'))).items():
    icons[k] = {kk: vv for kk, vv in v.items() if kk != 'source'}

with open(OUT, 'w') as o:
    o.write('// GENERATED by scripts/gen-icons.py from the compose module\'s res/drawable — do not edit.\n')
    o.write('/* eslint-disable */\n\n')
    o.write('export interface IconPath { d: string; fill: string; stroke?: string; strokeWidth?: number;\n')
    o.write('  strokeLinecap?: string; strokeLinejoin?: string; fillRule?: string; fillOpacity?: number; strokeOpacity?: number }\n')
    o.write('export interface IconDef { w: number; h: number; vw: number; vh: number; paths: IconPath[] }\n\n')
    o.write('export const ICONS = ' + json.dumps(icons, indent=1) + ' satisfies Record<string, IconDef>;\n\n')
    o.write('export type IconName = keyof typeof ICONS;\n')
print(f'{len(icons)} icons → {os.path.relpath(OUT)}')
