/* FarmerChat Theme Studio — "Get SDK" view.
 *
 * This tab is the integration guide and nothing else. It previously also carried
 * four per-platform download cards (themed initialize() snippets, quick-start .md,
 * version selector); those were removed on request. `lib/sdk.ts` still holds the
 * grounded per-platform metadata and is what the version sentence below derives
 * from, so the cards can be restored without re-establishing any of those facts.
 *
 * Content comes from `lib/guide.data.json`, generated by `tools/guide-gen/build.py`
 * from the same model as the shareable artifact — the two cannot drift. */
import { SDK_META } from "@/lib/sdk"
import { IntegrationGuide } from "@/components/IntegrationGuide"

/** "Android publishes 2.0.0; Web, React Native and iOS publish 1.0.0" — derived
 *  from SDK_META, never hardcoded, so bumping a podspec cannot make this lie. */
function versionSummary() {
  const byVersion = new Map<string, string[]>()
  for (const m of SDK_META) {
    const v = m.versions[0]
    byVersion.set(v, [...(byVersion.get(v) ?? []), m.name])
  }
  return [...byVersion.entries()]
    .sort((a, b) => b[0].localeCompare(a[0], undefined, { numeric: true }))
    .map(([v, names]) => {
      const list =
        names.length > 1 ? `${names.slice(0, -1).join(", ")} and ${names[names.length - 1]}` : names[0]
      return `${list} ${names.length > 1 ? "publish" : "publishes"} ${v}`
    })
    .join("; ")
}

export function SdkDownloads() {
  return (
    <div className="mx-auto max-w-[1300px] px-4 py-6 lg:px-6">
      <div className="mb-6">
        <h1 className="text-lg font-bold">Integration guide</h1>
        <p className="mt-1 max-w-[74ch] text-sm text-muted-foreground">
          End-to-end setup for every flavour the SDK ships — Android (Compose and XML Views),
          iOS (SwiftUI, UIKit and Objective-C), React Native and Web. Each one follows the same
          section order, so you can compare platforms line for line. Versions differ per platform:{" "}
          {versionSummary()}.
        </p>
      </div>
      <IntegrationGuide />
    </div>
  )
}
