/**
 * Labels — server-driven label base keys, copied 1:1 from the Android SDK
 * core `Labels.kt` (itself ported from the app's core/labels/Labels.kt).
 * Keys resolve via LabelManager: `${key}_${lang}` → `${key}_en` → fallback.
 */
export const Labels = {
  FARMERCHAT_STARTING: 'fc_v2_app_label_farmerchat_starting',
  CHOOSE_YOUR_LANGUAGE: 'fc_v2_app_label_choose_your_language',
  YOU_CHANGE_LATER: 'fc_v2_app_label_you_change_later',
  FARMERCHAT_TAGLINE: 'fc_v2_app_label_farmerchat_tagline',
  START_USING_FARMERCHAT: 'fc_v2_app_label_start_using_farmerchat',
  TERMS_PRIVACY_AGREEMENT: 'fc_v2_app_label_terms_privacy_agreement',
  LOADING_LANGUAGES: 'fc_v2_app_label_loading_languages',
  TERMS_OF_USE: 'fc_v2_app_label_terms_of_use',
  PRIVACY_POLICY: 'fc_v2_app_label_privacy_policy',
  WHAT_SHOULD_WE_CALL_YOU: 'fc_v2_app_label_what_should_we_call_you',
  WE_GREET_YOU_NAME: 'fc_v2_app_label_we_greet_you_name',
  YOUR_NAME_OR_NICKNAME: 'fc_v2_app_label_your_name_or_nickname',
  SAVE_NAME: 'fc_v2_app_label_save_name',
  SAVING: 'fc_v2_app_label_saving',
  SKIP_FOR_NOW: 'fc_v2_app_label_skip_for_now',
  SIGN_UP: 'fc_v2_app_label_sign_up',
  ENTER_YOUR_PHONE_NUMBER: 'fc_v2_app_label_enter_your_phone_number',
  ENTER_PHONE_NUMBER: 'fc_v2_app_label_enter_phone_number',
  SEND_OTP_SIGNIN: 'fc_v2_app_label_send_otp_signin',
  SEND_OTP_SIGNIN_SHORT: 'fc_v2_app_label_send_otp_signin_short',
  SEND_ONE_TIME_CODE: 'fc_v2_app_label_send_one_time_code',
  SEND_VIA_WHATSAPP: 'fc_v2_app_label_send_via_whatsapp',
  SEND_VIA_SMS: 'fc_v2_app_label_send_via_sms',
  SENDING_CODE: 'fc_v2_app_label_sending_code',
  PLEASE_CHECK_TRY_AGAIN: 'fc_v2_app_label_please_check_try_again',
  BY_CONTINUING_TO_VERIFICATION_YOU_ARE_ACCEPTING_OUR: 'fc_v2_app_label_by_continuing_to_verification_you_are_accepting_our',
  PLEASE_ALSO_SEE_OUR: 'fc_v2_app_label_please_also_see_our',
  UNKNOWN_ERROR: 'fc_v2_app_label_unknown_error',
  UNABLE_TO_LOAD_LEGAL_LINKS: 'fc_v2_app_label_unable_to_load_legal_links',
  PLEASE_ENTER_A_VALID_NUMBER: 'fc_v2_app_label_please_enter_a_valid_number',
  ENTER_CODE_WE_SENT: 'fc_v2_app_label_enter_code_we_sent',
  CHECK_YOUR_MESSAGES_CODE: 'fc_v2_app_label_check_your_messages_code',
  VERIFY: 'fc_v2_app_label_verify',
  VERIFYING: 'fc_v2_app_label_verifying',
  START_OVER: 'fc_v2_app_label_start_over',
  PLEASE_ENTER: 'fc_v2_app_label_please_enter',
  SECONDS: 'fc_v2_app_label_seconds',
  RESEND_CODE: 'fc_v2_app_label_resend_code',
  SELECT_COUNTRY_CODE: 'fc_v2_app_label_select_country_code',
  SEARCH: 'fc_v2_app_label_search',
  COUNTRY_PHONE_FORMAT: 'fc_v2_app_label_country_phone_format',
  SAVE_SELECTION: 'fc_v2_app_label_save_selection',
  COUNTRY_CODE: 'fc_v2_app_label_country_code',
  SAVE: 'fc_v2_app_label_save',
  CANCEL: 'fc_v2_app_label_cancel',
  CHOOSE_SIM_NUMBER: 'fc_v2_app_label_choose_sim_number',
  CLOSE: 'fc_v2_app_label_close',
  ALL_SET: 'fc_v2_app_label_all_set',
  PREVIOUS_QUESTIONS_MENU: 'fc_v2_app_label_previous_questions_menu',
  CONTINUE: 'fc_v2_app_label_continue',
  YOURE_ALL_SET: 'fc_v2_app_label_youre_all_set',
  HOW_WE_HELP_YOU_MORNING: 'fc_v2_app_label_how_we_help_you_morning',
  WHAT_DO_YOU_NEED_HELP_TODAY: 'fc_v2_app_label_what_do_you_need_help_today',
  HOWS_FARM_LOOKING_MORNING: 'fc_v2_app_label_hows_farm_looking_morning',
  HOW_WE_HELP_YOU_TODAY: 'fc_v2_app_label_how_we_help_you_today',
  WHAT_WE_HELP_YOU: 'fc_v2_app_label_what_we_help_you',
  HOWS_FARM_GOING_TODAY: 'fc_v2_app_label_hows_farm_going_today',
  HOW_WE_HELP_YOU_EVENING: 'fc_v2_app_label_how_we_help_you_evening',
  NEED_HELP_ANYTHING_TODAY: 'fc_v2_app_label_need_help_anything_today',
  HOW_DID_THINGS_GO_TODAY: 'fc_v2_app_label_how_did_things_go_today',
  GETTING_TODAYS_ADVICE: 'fc_v2_app_label_getting_todays_advice',
  GETTING_YOUR_LOCATION: 'fc_v2_app_label_getting_your_location',
  FOR_YOUR_FARM_TODAY: 'fc_v2_app_label_for_your_farm_today',
  CHECK_YOUR_INTERNET_CONNECTION: 'fc_v2_app_label_check_your_internet_connection',
  HELLO: 'fc_v2_app_label_hello',
  COMEBACK_TOMORROW: 'fc_v2_app_label_comeback_tomorrow',
  WHAT_WRONG_MY_CROP: 'fc_v2_app_label_what_wrong_my_crop',
  READ_FULL_ADVICE: 'fc_v2_app_label_read_full_advice',
  SAVED_TO_GALLERY: 'fc_v2_app_label_saved_to_gallery',
  FAILED_TO_SAVE: 'fc_v2_app_label_failed_to_save',
  AUDIO_NOT_AVAILABLE: 'fc_v2_app_label_audio_not_available',
  NO_AUDIO_AVAILABLE_MESSAGE: 'fc_v2_app_label_no_audio_available_message',
  SHARE_APP_MESSAGE: 'fc_v2_app_label_share_app_message',
  RECENT_CHATS: 'fc_v2_app_label_recent_chats',
  LOADING_CHATS: 'fc_v2_app_label_loading_chats',
  LOADING_MORE: 'fc_v2_app_label_loading_more',
  COULDNT_LOAD_MORE_CHATS: 'fc_v2_app_label_couldnt_load_more_chats',
  TRY_AGAIN: 'fc_v2_app_label_try_again',
  NEW_CONVERSATION: 'fc_v2_app_label_new_conversation',
  SETTINGS: 'fc_v2_app_label_settings',
  APPEARANCE: 'fc_v2_app_label_appearance',
  DAY: 'fc_v2_app_label_day',
  NIGHT: 'fc_v2_app_label_night',
  AUTO: 'fc_v2_app_label_auto',
  FARMERCHAT_ALWAYS_LIGHT_MODE: 'fc_v2_app_label_farmerchat_always_light_mode',
  FARMERCHAT_ALWAYS_DARK_MODE: 'fc_v2_app_label_farmerchat_always_dark_mode',
  FARMERCHAT_ADJUSTS_YOUR_PHONE_SETTINGS: 'fc_v2_app_label_farmerchat_adjusts_your_phone_settings',
  ACCOUNT_DETAILS: 'fc_v2_app_label_account_details',
  YOUR_NAME: 'fc_v2_app_label_your_name',
  LOGOUT: 'fc_v2_app_label_logout',
  YOUR_NAME_HAS_UPDATED: 'fc_v2_app_label_your_name_has_updated',
  ALL_LANGUAGES: 'fc_v2_app_label_all_languages',
  APPLY_LANGUAGE: 'fc_v2_app_label_apply_language',
  APPLYING_LANGUAGE: 'fc_v2_app_label_applying_language',
  SAVE_LANGUAGE: 'fc_v2_app_label_save_language',
  SETTING_LANGUAGE: 'fc_v2_app_label_setting_language',
  LANGUAGE_UPDATED: 'fc_v2_app_label_language_updated',
  NAME: 'fc_v2_app_label_name',
  ENTER_YOUR_NAME: 'fc_v2_app_label_enter_your_name',
  HELP: 'fc_v2_app_label_help',
  HOW_TO_USE_FARMERCHAT: 'fc_v2_app_label_how_to_use_farmerchat',
  NO_FAQS_AVAILABLE: 'fc_v2_app_label_no_faqs_available',
  LINK_UNAVAILABLE: 'fc_v2_app_label_link_unavailable',
  MORE: 'fc_v2_app_label_more',
  FARMERCHAT_V200: 'fc_v2_app_label_farmerchat_v200',
  DIGITAL_GREEN: 'fc_v2_app_label_digital_green',
  NO_INTERNET_CONNECTION: 'fc_v2_app_label_no_internet_connection',
  FARMERCHAT_NEEDS_THE_INTERNET: 'fc_v2_app_label_farmerchat_needs_the_internet',
  CHECK_MOBILE_DATA_WIFI_SIGNAL: 'fc_v2_app_label_check_mobile_data_wi-fi_signal',
  SOMETHING_WENT_WRONG: 'fc_v2_app_label_something_went_wrong',
  FARMERCHAT_COULDNT_LOAD: 'fc_v2_app_label_farmerchat_couldnt_load',
  PLEASE_TRY_AGAIN: 'fc_v2_app_label_please_try_again',
  CAMERA_PERMISSION_REQUIRED: 'fc_v2_app_label_camera_permission_required',
  MICROPHONE_PERMISSION_REQUIRED: 'fc_v2_app_label_microphone_permission_required',
  PLEASE_ENABLE_CAMERA_SETTINGS: 'fc_v2_app_label_please_enable_camera_settings',
  PLEASE_ENABLE_MICROPHONE_SETTINGS: 'fc_v2_app_label_please_enable_microphone_settings',
  GO_TO_SETTINGS: 'fc_v2_app_label_go_to_settings',
  CAMERA: 'fc_v2_app_label_camera',
  GALLERY: 'fc_v2_app_label_gallery',
  NO_CAMERA_APP_AVAILABLE: 'fc_v2_app_label_no_camera_app_available',
  SHARE_LOCATION: 'fc_v2_app_label_share_location',
  GET_ADVICE_YOUR_AREA: 'fc_v2_app_label_get_advice_your_area',
  LOCATION_HELPS_SUGGESTIONS: 'fc_v2_app_label_location_helps_suggestions',
  TURN_LOCATION_ON_NOW: 'fc_v2_app_label_turn_location_on_now',
  CONTINUE_WITHOUT_LOCATION: 'fc_v2_app_label_continue_without_location',
  WE_NEED_YOUR_LOCATION: 'fc_v2_app_label_we_need_your_location',
  LOCATION_TAILOR_ADVICE: 'fc_v2_app_label_location_tailor_advice',
  TURN_ON_IN_SETTINGS: 'fc_v2_app_label_turn_on_in_settings',
  TURN_ON_GPS: 'fc_v2_app_label_turn_on_gps',
  GET_LOCAL_ADVICE: 'fc_v2_app_label_get_local_advice',
  LOCATION_GPS_TURNED_OFF: 'fc_v2_app_label_location_gps_turned_off',
  TURNING_HELPS_TAILOR_ANSWERS_YOUR_AREA: 'fc_v2_app_label_turning_helps_tailor_answers_your_area',
  COULDNT_GET_YOUR_LOCATION: 'fc_v2_app_label_couldnt_get_your_location',
  PRACTICAL_ADVICE_YOUR_FARM: 'fc_v2_app_label_practical_advice_your_farm',
  TURN_ON_LOCATION: 'fc_v2_app_label_turn_on_location',
  LOCATION_WEATHER_ADVICE: 'fc_v2_app_label_location_weather_advice',
  LOCATION_GPS_TURNED_OFF_TURNING_HELPS: 'fc_v2_app_label_location_gps_turned_off_turning_helps',
  SHARE_DOWNLOAD: 'fc_v2_app_label_share_download',
  SKIP: 'fc_v2_app_label_skip',
  BACK: 'fc_v2_app_label_back',
  NO_NETWORK: 'fc_v2_app_label_no_network',
  PLEASE_CONNECT_INTERNET_TRY_AGAIN: 'fc_v2_app_label_please_connect_internet_try_again',
  FARMERCHAT: 'fc_v2_app_label_farmerchat',
  SAVE_YOUR_QUESTIONS_ANSWERS: 'fc_v2_app_label_save_your_questions_answers',
  WELL_SAVE_YOUR_CHATS_YOU_CONTINUE: 'fc_v2_app_label_well_save_your_chats_you_continue',
  SIGN_UP_PHONE_NUMBER: 'fc_v2_app_label_sign_up_phone_number',
  ASK_A_FOLLOWUP_QUESTIONS: 'fc_v2_app_label_ask_a_followup_questions',
  ASK_SPECIFIC_CROPS: 'fc_v2_app_label_ask_specific_crops',
  UPLOAD_PHOTOS_PLANT_DISEASE_IDENTIFICATION: 'fc_v2_app_label_upload_photos_plant_disease_identification',
  LOCATION_UPDATED: 'fc_v2_app_label_location_updated',
  HOME: 'fc_v2_app_label_home',
  SEE_ALL: 'fc_v2_app_label_see_all',
  NO_CHATS_YET: 'fc_v2_app_label_no_chats_yet',
  HELP_SUPPORT: 'fc_v2_app_label_help_support',
  FAILED_TO_LOAD_CHATS: 'fc_v2_app_label_failed_to_load_chats',
  START_CHAT: 'fc_v2_app_label_start_chat',
  CANT_LOAD_RIGHT_NOW: 'fc_v2_app_label_cant_load_right_now',
  GETTING_YOUR_ANSWER: 'fc_v2_app_label_getting_your_answer',
  PHOTO: 'fc_v2_app_label_photo',
  SPEAK: 'fc_v2_app_label_speak',
  TYPE: 'fc_v2_app_label_type',
  LANGUAGE: 'fc_v2_app_label_language',
  FAQ: 'fc_v2_app_label_faq',
  WHAT_IS_WRONG_WITH_MY_CROP: 'fc_v2_app_label_what_is_wrong_with_my_crop',
  ASR_IS_DISABLED_FOR_YOUR_SELECTED_LANGUAGE: 'fc_v2_app_label_asr_is_disabled_for_your_selected_language',
  FAILED_TO_LOAD_CHAT_HISTORY: 'fc_v2_app_label_failed_to_load_chat_history',
  FAILED_TO_PROCESS_IMAGE: 'fc_v2_app_label_failed_to_process_image',
  FAILED_TO_GET_RESPONSE: 'fc_v2_app_label_failed_to_get_response',
  SOMETHING_WENT_WRONG_PLEASE_TRY_AGAIN: 'fc_v2_app_label_something_went_wrong_please_try_again',
  REQUEST_TIMED_OUT_PLEASE_TRY_AGAIN: 'fc_v2_app_label_request_timed_out_please_try_again',
  TRANSCRIPTION_FAILED_PLEASE_TRY_AGAIN: 'fc_v2_app_label_transcription_failed_please_try_again',
  SETTING_LOADING_STATE_IMMEDIATELY_GPS_FETCH_IN_PROGRESS: 'fc_v2_app_label_setting_loading_state_immediately_gps_fetch_in_progress',
  BY_CONTINUING_YOU_AGREE_TO_OUR: 'fc_v2_app_label_by_continuing_you_agree_to_our',
  ALSO_SEE: 'fc_v2_app_label_also_see',
  LOADING: 'fc_v2_app_label_loading',
  PLEASE_ENTER_A_VALID_OTP: 'fc_v2_app_label_please_enter_a_valid_otp',
  LISTEN: 'fc_v2_app_label_listen',
  THANK_YOU_YOUR_ANSWER_HELPS_US_GIVE_MORE_ACCURATE_ADVICE: 'fc_v2_app_label_thank_you_your_answer_helps_us_give_more_accurate_advice',
  CONFIRM: 'fc_v2_app_label_confirm',
  ASK: 'fc_v2_app_label_ask',
  PHOTOS: 'fc_v2_app_label_photos',
  EITHER_ICONRES_OR_IMAGEVECTOR_MUST_BE_PROVIDED_WHEN_NOT_LOADING: 'fc_v2_app_label_either_iconRes_or_imageVector_must_be_provided_when_not_loading',
  SEND: 'fc_v2_app_label_send',
  VOICE: 'fc_v2_app_label_voice',
  MICROPHONE_PERMISSION_IS_REQUIRED_FOR_VOICE_INPUT: 'fc_v2_app_label_microphone_permission_is_required_for_voice_input',
  FAILED_TO_START_RECORDING: 'fc_v2_app_label_failed_to_start_recording',
  TRANSCRIPTION_UNCLEAR: 'fc_v2_app_label_transcription_unclear',
  FAILED_TO_PROCESS_AUDIO: 'fc_v2_app_label_failed_to_process_audio',
  NO_AUDIO_RECORDED_OR_CONVERSATION_NOT_STARTED: 'fc_v2_app_label_no_audio_recorded_or_conversation_not_started',
  LISTENING: 'fc_v2_app_label_listening',
  PROCESSING: 'fc_v2_app_label_processing',
  ASK_YOUR_FARMING_QUESTION: 'fc_v2_app_label_ask_your_farming_question',
  ONE_SECOND_PLEASE: 'fc_v2_app_label_one_second_please',
  VOICE_INPUT_IS_STILL_IMPROVING: 'fc_v2_app_label_voice_input_is_still_improving',
  HAVE_A_GREAT_DAY_COME_BACK_TOMORROW: 'fc_v2_app_label_have_a_great_day_come_back_tomorrow',
  TIPS_LIST_CANNOT_BE_EMPTY: 'fc_v2_app_label_tips_list_cannot_be_empty',
  THIS_FUNCTION_REQUIRED_ENABLE_IN_DEVICE_SETTINGS: 'fc_v2_app_label_this_permission_is_needed_for_the_app_to_function_properly_please_enable_it_in_your_device_settings',
  ASK_ABOUT_YOUR_FARM: 'fc_v2_app_label_ask_about_your_farm',
  PERMISSIONS_ARE_REQUIRED_TO_AUTO_DETECT_SIM_NUMBER: 'fc_v2_app_label_permissions_are_required_to_auto_detect_sim_number.',
  ASK_A_FOLLOWUP: 'fc_v2_app_label_ask_a_followup_questions',
  STORAGE_EXCEEDED: 'fc_v2_app_label_storage_exceeded',
  USER_CANCELLED_OR_USER_PROVIDER_ERROR: 'fc_v2_app_label_user_cancelled_or_provider_error',
  YOU_CAN_ASK_FOLLOWUP_QUESTIONS_TO_GET_MORE_DETAILS: 'fc_v2_app_label_tips_you_can_ask_followup_questions_to_get_more_details',
  UPLOAD_PHOTOS_FOR_PLANT_DISEASE_IDENTIFICATION: 'fc_v2_app_label_tips_upload_photos_for_plant_disease_identification',
  AI_MAY_BE_WRONG_PLEASE_DOUBLE_CHECK: 'fc_v2_app_label_tips_ai_may_be_wrong_please_double_check',
  RELATED_QUESTIONS: 'fc_v2_app_label_related_questions',
  CHOOSE_A_FOLLOWUP_OPTION_BELOW: 'fc_v2_app_label_choose_a_followup_option_below',
  OR_ASK_A_FOLLOWUP_QUESTIONS: 'fc_v2_app_label_or_ask_a_followup_questions',
  GET_STARTED_BY_CLICKING_ON_PHOTO_SPEAK_OR_TYPE_TO_ASK_YOUR_QUESTION: 'fc_v2_app_label_get_started_by_clicking_on_photo_speak_or_type_to_ask_your_question',
  WHAT_IS_THE_PRESENT_WEATHER: 'fc_v2_app_label_what_is_the_present_weather',
  DID_YOU_KNOW: 'fc_v2_app_label_tips_did_you_know',
  QUICK_TIP: 'fc_v2_app_label_tips_quick_tip',
  TRY_THIS: 'fc_v2_app_label_tips_try_this',
  INVALID_REQUEST_PLEASE_TRY_AGAIN: 'fc_v2_app_label_invalid_request_please_try_again',
  SESSION_EXPIRED_PLEASE_LOGIN_AGAIN: 'fc_v2_app_label_session_expired_please_login_again',
  ACCESS_DENIED: 'fc_v2_app_label_access_denied',
  SERVICE_NOT_FOUND: 'fc_v2_app_label_service_not_found',
  NETWORK_IS_SLOW_PLEASE_TRY_AGAIN: 'fc_v2_app_label_network_is_slow_please_try_again',
  TOO_MANY_REQUESTS_PLEASE_TRY_AGAIN_LATER: 'fc_v2_app_label_too_many_requests_please_try_later',
  SERVER_IS_BUSY_PLEASE_TRY_AGAIN: 'fc_v2_app_label_server_is_busy_please_try_again',
  UNABLE_TO_CONNECT_PLEASE_TRY_AGAIN: 'fc_v2_app_label_unable_to_connect_please_try_again',
  SECURE_CONNECTION_FAILED: 'fc_v2_app_label_secure_connection_failed',
  NETWORK_ERROR_PLEASE_TRY_AGAIN: 'fc_v2_app_label_network_error_please_try_again',
  NAME_MUST_BE_AT_LEAST: 'fc_v2_app_label_name_must_be_at_least',
  NAME_MUST_BE_AT_MOST: 'fc_v2_app_label_name_must_be_at_most',
  CHARACTERS: 'fc_v2_app_label_characters',
  FARMERCHAT_PRACTICAL_ADVICE_FOR_YOUR_CROPS_AND_ANIMALS: 'fc_v2_app_label_farmerchat_tagline',
  GET_STARTED: 'fc_v2_app_label_get_started',
  BY_TAPPING_GET_STARTED_YOU_AGREE_TO_OUR: 'fc_v2_app_label_by_tapping_get_started_you_agree_to_our',
  SSFR_ADVISORY: 'fc_v2_app_label_ssfr_advisory',
  SSFR_ADVISORY_DESCRIPTION: 'fc_v2_app_label_ssfr_advisory_description',
  SSFR_WHEAT: 'fc_v2_app_label_ssfr_wheat',
  SSFR_MAIZE: 'fc_v2_app_label_ssfr_maize',
  SSFR_WHEAT_QUESTION: 'fc_v2_app_label_ssfr_wheat_question',
  SSFR_MAIZE_QUESTION: 'fc_v2_app_label_ssfr_maize_question',

  // ---- agentic streaming (2.0.0) ----
  /** "Connection stopped. Your partial answer is saved." */
  CONNECTION_STOPPED_PARTIAL_SAVED: 'fc_v2_app_label_connection_stopped_partial_saved',
  /** "Paused, resuming…" — transient stall hint while a stream is mid-answer. */
  RESPONSE_PAUSED_RESUMING: 'fc_v2_app_label_response_paused_resuming',

  // ---- alignment surfaces (2.0.0). All verified present on endpoint #3. ----
  /** "Share location" — GPS_PROMPT heading. */
  SHARE_LOCATION_TITLE: 'fc_v2_app_label_share_location_title',
  /**
   * Sent as the query when the farmer declines the GPS_PROMPT surface, so the blocking question
   * still resolves. Verified present on endpoint #3; the English fallback
   * "Continue without sharing my location" is kept as the usual safety net.
   */
  LOCATION_PERMISSION_DECLINED: 'fc_v2_app_label_location_permission_declined',
  /** "Add one clear photo" — UPLOAD_PHOTO heading. */
  ADD_ONE_CLEAR_PHOTO: 'fc_v2_app_label_add_one_clear_photo',
  /** "Please Confirm" — CONFIRM heading. */
  PLEASE_CONFIRM: 'fc_v2_app_label_please_confirm',
  /** "Choose one" — CLARIFY heading. */
  CHOOSE_ONE: 'fc_v2_app_label_choose_one',
  /** "Don't see your option?" — escape-hatch hint. */
  DONT_SEE_YOUR_OPTION: 'fc_v2_app_label_dont_see_your_option',
  /** "Type or say it." — escape-hatch action. */
  TYPE_OR_SAY_IT: 'fc_v2_app_label_type_or_say_it',

  // ---- location + terms (2.0.0). Verbatim from the Android core `Labels.kt`
  // (SET_YOUR_LOCATION..ACCEPT_AND_CONTINUE at :333-341, YOUR_LOCATION at :362),
  // all verified present on endpoint #3. ----
  /** "Set your location" — Home location pill, invite state. */
  SET_YOUR_LOCATION: 'fc_v2_app_label_set_your_location',
  /** "Location found" — Home location pill, success state. */
  LOCATION_FOUND: 'fc_v2_app_label_location_found',
  /** "Change" — trailing accent on the located pill. */
  CHANGE: 'fc_v2_app_label_change',
  /** "Allow location in Settings" — Home location pill, permission-blocked state. */
  ALLOW_LOCATION_IN_SETTINGS: 'fc_v2_app_label_allow_location_in_settings',
  /** "Accept and continue" — TermsOfUseDialog primary action. */
  ACCEPT_AND_CONTINUE: 'fc_v2_app_label_accept_and_continue',
  /** "Your location:" — caption above the address on the location chat bubble. */
  YOUR_LOCATION: 'fc_v2_app_label_your_location',

  // ---- Settings "My Farm" location row (2.0.0). Verbatim from the Android core `Labels.kt`
  // (MY_FARM..LOCATION_HELPER_CHANGE_ANYTIME at :373-385); all seven are in
  // test/fixtures/servedLabelKeys.json. ----
  /** "My Farm" — settings section heading. */
  MY_FARM: 'fc_v2_app_label_my_farm',
  /** "Location" */
  LOCATION: 'fc_v2_app_label_location',
  /** "Estimated" — location precision caption. */
  ESTIMATED: 'fc_v2_app_label_estimated',
  /** "approximate" — location precision badge. */
  APPROXIMATE: 'fc_v2_app_label_approximate',
  /** "Share your location for better advice." */
  LOCATION_HELPER_SHARE: 'fc_v2_app_label_share_your_location_for_better_advice',
  /** "Advice and weather for this area." */
  LOCATION_HELPER_ADVICE_WEATHER: 'fc_v2_app_label_advice_and_weather_for_this_area',
  /** "Change anytime." */
  LOCATION_HELPER_CHANGE_ANYTIME: 'fc_v2_app_label_change_anytime',
} as const;

export type LabelKey = (typeof Labels)[keyof typeof Labels];
